version: '3'

services:

  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    container_name: frontend_dev
    command: npm run start
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/home/app/frontend/src
    stdin_open: true
    tty: true

  backend:
    build: ./backend
    container_name: backend
    command: >
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done;  python
      /home/app/backend/manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    env_file:
      - ./backend/config/.env.dev
    volumes:
      - ./backend:/home/app/backend
      - static_volume:/home/app/backend/static
      - media_volume:/home/app/backend/media
    depends_on:
      - frontend
      - db

  db:
    image: postgres:13-alpine
    container_name: db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./backend/config/.env.dev
    ports:
      - '5432:5432'

volumes:
  db: null
  static_volume: null
  media_volume: null
