version: '3'

services:

  frontend_nginx:
    build:
      dockerfile: Dockerfile.http
      context: ./frontend
    container_name: frontend_nginx
    ports:
      - 80:80
    volumes:
      - ./backend/nginx/nginx.http.conf:/etc/nginx/conf.d/nginx.conf
      - static_volume:/home/app/backend/django_static
      - media_volume:/home/app/backend/media
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    command: >
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done;  gunicorn
      config.wsgi:application --bind 0.0.0.0:8000'
    expose:
      - 8000
    env_file:
      - ./backend/config/.env.prod
    volumes:
      - ./backend:/home/app/backend
      - static_volume:/home/app/backend/django_static
      - media_volume:/home/app/backend/media
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./backend/config/.env.prod
    ports:
      - '5432:5432'

volumes:
  db: null
  static_volume: null
  media_volume: null
